// Shared generation core: snapshot normalization and type generation.
// Used by scripts/openapi-update.mjs, scripts/openapi-generate.mjs and test/generation.test.ts
// so the committed artifacts and the drift check can never disagree about how output is produced.
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

export const SNAPSHOT_PATH = fileURLToPath(
  new URL("../openapi/valoasset-v1.json", import.meta.url),
);
export const GENERATED_TYPES_PATH = fileURLToPath(
  new URL("../src/generated/openapi.ts", import.meta.url),
);
export const GENERATED_ALIASES_PATH = fileURLToPath(
  new URL("../src/generated/aliases.ts", import.meta.url),
);

/** Schemas that are protocol plumbing, not business DTOs; they get no public alias. */
const NON_BUSINESS_SCHEMAS = new Set(["ApiError"]);

/**
 * Deterministic snapshot form: objects get their keys sorted recursively (JSON object member
 * order carries no meaning), arrays keep their order (it does), 2-space indent, trailing newline.
 */
export function normalizeDocument(document) {
  return `${JSON.stringify(sortKeysDeep(document), null, 2)}\n`;
}

function sortKeysDeep(value) {
  if (Array.isArray(value)) {
    return value.map(sortKeysDeep);
  }
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortKeysDeep(value[key])]),
    );
  }
  return value;
}

export async function readSnapshot() {
  return JSON.parse(await readFile(SNAPSHOT_PATH, "utf8"));
}

/** openapi-typescript output for the given document. Internal — never exported from the package root. */
export async function generateOpenApiTypes(document) {
  const ast = await openapiTS(document, {
    // Business DTOs use exact server field sets; unknown-field laxness belongs to consumers.
    additionalProperties: false,
  });
  return astToString(ast);
}

/**
 * Stable business-type aliases over the generated components. Mechanical on purpose: the alias
 * list is exactly the snapshot's component schemas minus protocol types, sorted by name.
 */
export function generateAliases(document) {
  const schemaNames = Object.keys(document.components?.schemas ?? {})
    .filter((name) => !NON_BUSINESS_SCHEMAS.has(name))
    .sort();

  const lines = [
    "// Auto-generated by scripts/openapi-generate.mjs from openapi/valoasset-v1.json — do not edit.",
    'import type { components } from "./openapi.js";',
    "",
    ...schemaNames.map((name) => `export type ${name} = components["schemas"]["${name}"];`),
  ];
  return `${lines.join("\n")}\n`;
}
